[2025-10-18T03:29:00.301+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.data_processing.validate_data_quality manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T03:29:00.306+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.data_processing.validate_data_quality manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T03:29:00.306+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 4
[2025-10-18T03:29:00.313+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_processing.validate_data_quality> on 2025-10-18 02:31:24.144743+00:00
[2025-10-18T03:29:00.316+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2025-10-18T03:29:00.318+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agricultural_sri_annual_report', 'data_processing.validate_data_quality', 'manual__2025-10-18T02:31:24.144743+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/agricultural_sri_pipeline.py', '--cfg-path', '/tmp/tmpo93nyi2h']
[2025-10-18T03:29:00.319+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask data_processing.validate_data_quality
[2025-10-18T03:29:00.345+0000] {task_command.py:416} INFO - Running <TaskInstance: agricultural_sri_annual_report.data_processing.validate_data_quality manual__2025-10-18T02:31:24.144743+00:00 [running]> on host 4e2b74bc69c8
[2025-10-18T03:29:00.380+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alerts@agcompany.com' AIRFLOW_CTX_DAG_OWNER='agricultural_risk_team' AIRFLOW_CTX_DAG_ID='agricultural_sri_annual_report' AIRFLOW_CTX_TASK_ID='data_processing.validate_data_quality' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T02:31:24.144743+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T02:31:24.144743+00:00'
[2025-10-18T03:29:00.604+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/context.py:314: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2025-10-18T03:29:00.604+0000] {agricultural_sri_pipeline.py:221} INFO - üîç Validating data quality for 2025
[2025-10-18T03:29:00.620+0000] {data_validator.py:335} INFO - üîç Validating all datasets...
[2025-10-18T03:29:00.620+0000] {data_validator.py:32} INFO -   Validating crop yield data...
[2025-10-18T03:29:00.623+0000] {data_validator.py:108} INFO -     ‚úì Crop data valid: 380 records, 39 states
[2025-10-18T03:29:00.623+0000] {data_validator.py:129} INFO -   Validating weather data...
[2025-10-18T03:29:00.625+0000] {data_validator.py:184} INFO -     ‚úì Weather data valid: 50 records, 50 states
[2025-10-18T03:29:00.625+0000] {data_validator.py:205} INFO -   Validating drought data...
[2025-10-18T03:29:00.626+0000] {data_validator.py:272} INFO -   Validating economic data...
[2025-10-18T03:29:00.627+0000] {data_validator.py:311} INFO -     ‚úì Economic data valid: 3 records, 3 commodities
[2025-10-18T03:29:00.627+0000] {data_validator.py:367} ERROR - ‚ùå Validation failed: 1 errors, 1 warnings
[2025-10-18T03:29:00.627+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/agricultural_sri_pipeline.py", line 237, in validate_data_quality
    if not validation_results['passed']:
KeyError: 'passed'
[2025-10-18T03:29:00.631+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=agricultural_sri_annual_report, task_id=data_processing.validate_data_quality, execution_date=20251018T023124, start_date=20251018T032900, end_date=20251018T032900
[2025-10-18T03:29:00.636+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task data_processing.validate_data_quality ('passed'; 67)
[2025-10-18T03:29:00.667+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-18T03:29:00.681+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
