[2025-10-18T04:14:30.364+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.sri_calculation.validate_sri_model manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:14:30.371+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: agricultural_sri_annual_report.sri_calculation.validate_sri_model manual__2025-10-18T02:31:24.144743+00:00 [queued]>
[2025-10-18T04:14:30.373+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2025-10-18T04:14:30.381+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sri_calculation.validate_sri_model> on 2025-10-18 02:31:24.144743+00:00
[2025-10-18T04:14:30.385+0000] {standard_task_runner.py:57} INFO - Started process 837 to run task
[2025-10-18T04:14:30.387+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'agricultural_sri_annual_report', 'sri_calculation.validate_sri_model', 'manual__2025-10-18T02:31:24.144743+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/agricultural_sri_pipeline.py', '--cfg-path', '/tmp/tmp1sxx5og7']
[2025-10-18T04:14:30.388+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask sri_calculation.validate_sri_model
[2025-10-18T04:14:30.414+0000] {task_command.py:416} INFO - Running <TaskInstance: agricultural_sri_annual_report.sri_calculation.validate_sri_model manual__2025-10-18T02:31:24.144743+00:00 [running]> on host 4e2b74bc69c8
[2025-10-18T04:14:30.445+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alerts@agcompany.com' AIRFLOW_CTX_DAG_OWNER='agricultural_risk_team' AIRFLOW_CTX_DAG_ID='agricultural_sri_annual_report' AIRFLOW_CTX_TASK_ID='sri_calculation.validate_sri_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-18T02:31:24.144743+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-18T02:31:24.144743+00:00'
[2025-10-18T04:14:30.668+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/agricultural_sri_pipeline.py", line 342, in validate_sri_model
    from sri_validator import validate_sri_output
ImportError: cannot import name 'validate_sri_output' from 'sri_validator' (/opt/airflow/dags/scripts/models/sri_validator.py)
[2025-10-18T04:14:30.672+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=agricultural_sri_annual_report, task_id=sri_calculation.validate_sri_model, execution_date=20251018T023124, start_date=20251018T041430, end_date=20251018T041430
[2025-10-18T04:14:30.676+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task sri_calculation.validate_sri_model (cannot import name 'validate_sri_output' from 'sri_validator' (/opt/airflow/dags/scripts/models/sri_validator.py); 837)
[2025-10-18T04:14:30.703+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-18T04:14:30.714+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
